name: Daybreak
description: PortalRunner's Hardcore Server
version: 1.1.2
author: Pancake
website: "https://mgnet.work"

main: gay.pancake.daybreak.DaybreakPlugin
loader: gay.pancake.daybreak.DaybreakLoader
bootstrapper: gay.pancake.daybreak.DaybreakBootstrap
api-version: '1.20'
load: STARTUP

dependencies:
  server:
    Chunky:
      load: BEFORE
