name: Daybreak
description: PortalRunner's Hardcore Server
version: '1.0.0-SNAPSHOT'
author: Pancake
website: "https://mgnet.work"

main: de.pancake.daybreak.DaybreakPlugin
bootstrapper: de.pancake.daybreak.DaybreakBootstrap
api-version: '1.20'
load: POSTWORLD

dependencies:
  server:
    Chunky:
      load: BEFORE
